#pragma once

#include "AuxKernel.h"

/**
 * Auxiliary kernel responsible for computing the local power density
 * per unit volume generated by Joule heating.
 */
class JouleHeating : public AuxKernel
{
public:
  static InputParameters validParams();

  JouleHeating(const InputParameters & parameters);

protected:
  /**
   * AuxKernels MUST override computeValue.  computeValue() is called on
   * every quadrature point.  For Nodal Auxiliary variables those quadrature
   * points coincide with the nodes.
   */
  virtual Real computeValue() override;

  /// Holds the magnitude of the local electric field at the quadrature points
  const VectorVariableValue & _e_field;
  /// The local electrical_conductivity of the material.
  const MaterialProperty<Real> & _sigma;
};
